var artData={
	"church":{
		"displayName":"Church at Reversing Falls",
		"caption": "Watercolor - Framed size 20' x 24'",
		"modalImages":"images/imagesWater/Church.jpg", 
		"thumb":"images/imagesWater/Church_thumb.jpg",
		"paintingClass":"seaWater",
		},
	"drift":{
		"displayName":"Drift-In Beach, Port Clyde",
		"caption": "Watercolor - 16' x 20'",
		"modalImages":"images/imagesWater/Drift_In_Beach.jpg", 
		"thumb":"images/imagesWater/Drift_In_Beach_thumb.jpg",
		"paintingClass":"seaWater",
		},
	"fishShacks":{
		"displayName":"Fish Houses, Port Clyde",
		"caption": "Watercolor - 16' x 20'",
		"modalImages":"images/imagesWater/Fish_Shacks.jpg", 
		"thumb":"images/imagesWater/Fish_Shacks_thumb.jpg",
		"paintingClass":"seaWater",
		},
	"onRocks":{
		"displayName":"On the Rocks",
		"caption": 'Watercolor - 3 1/2" x 5 1/2"',
		"modalImages":"images/imagesWater/On_Rocks.jpg", 
		"thumb":"images/imagesWater/On_Rocks_thumb.jpg",
		"paintingClass":"seaWater",
		},
	"redHouse":{
		"displayName":"The Red House",
		"caption": 'Watercolor - 10" x 14", $495',
		"modalImages":"images/imagesWater/Red_house.jpg", 
		"thumb":"images/imagesWater/Red_house_thumb.jpg",
		"paintingClass":"seaWater",
		},
	"surfLobster":{
		"displayName":"Surf at Lobster Cove",
		"caption": 'Watercolor - 14" x 18" - $495',
		"modalImages":"images/imagesWater/Surf_at_Lobster_Cove.png", 
		"thumb":"images/imagesWater/Surf_at_Lobster_Cove_thumb.png",
		"paintingClass":"seaWater",
		},
	"window":{
		"displayName":"Through the Window, Manana, Monhegan",
		"caption": 'Watercolor - Framed 11" x 14"',
		"modalImages":"images/imagesWater/Through_the_Window.jpg", 
		"thumb":"images/imagesWater/Through_the_Window_thumb.jpg",
		"paintingClass":"seaWater",
		},
	"tidalCushing":{
		"displayName":"Tidal Cove, Cushing",
		"caption": 'Watercolor - Matted and Framed 16" x 20" - $250',
		"modalImages":"images/imagesWater/Tidal_Cushing.jpg", 
		"thumb":"images/imagesWater/Tidal_Cushing_thumb.jpg",
		"paintingClass":"seaWater",
		},
	"vinylhaven":{
		"displayName":"Surf at Vinylhaven",
		"caption": 'Watercolor - Matted and Framed 16" x 20" - $250',
		"modalImages":"images/imagesWater/Vinylhaven.jpg", 
		"thumb":"images/imagesWater/Vinylhaven_thumb.jpg",
		"paintingClass":"seaWater",
		},
	"washerwoman":{
		"displayName":"Washerwoman, Monhegan",
		"caption": 'Watercolor - Framed size: 19" x 23"',
		"modalImages":"images/imagesWater/Washerwoman.jpg", 
		"thumb":"images/imagesWater/Washerwoman_thumb.jpg",
		"paintingClass":"seaWater",
		},


	"fishhouse":{
		"displayName":"Fish House, South Thomaston",
		"caption": 'Oil - 18" x 24"',
		"modalImages":"images/imagesOil/Fish_House_Oil.jpg", 
		"thumb":"images/imagesOil/Fish_House_Oil_thumb.jpg",
		"paintingClass":"seaOil",
		},
	"lupines":{
		"displayName":"Lupines",
		"caption": 'Oil on Canvas - 16" x 20" - $495',
		"modalImages":"images/imagesOil/Lupines.jpg", 
		"thumb":"images/imagesOil/Lupines_thumb.jpg",
		"paintingClass":"seaOil",
		},
	"redRoof":{
		"displayName":"Red Roof at Marshall Point",
		"caption": 'Oil - 16" x 20" - Sold. Limited edition archival giclee prints available',
		"modalImages":"images/imagesOil/Red_Roof.jpg", 
		"thumb":"images/imagesOil/Red_Roof_thumb.jpg",
		"paintingClass":"seaOil",
		},
	"rocksRoses":{
		"displayName":"Rocks and Roses",
		"caption": 'Oil - 12" x 16" - Sold, prints available',
		"modalImages":"images/imagesOil/Rocks_Roses.jpg", 
		"thumb":"images/imagesOil/Rocks_Roses_thumb.jpg",
		"paintingClass":"seaOil",
		},
	"rockyCove":{
		"displayName":"Rocky Cove",
		"caption": '16" x 20" - Sold, prints available',
		"modalImages":"images/imagesOil/Rocky_Cove.jpg", 
		"thumb":"images/imagesOil/Rocky_Cove_thumb.jpg",
		"paintingClass":"seaOil",
		},
	"surfDance":{
		"displayName":"Surf Dance",
		"caption": 'Oil - 16" x 20" Sold',
		"modalImages":"images/imagesOil/Surf_Dance.jpg", 
		"thumb":"images/imagesOil/Surf_Dance_thumb.jpg",
		"paintingClass":"seaOil",
		},
	"symphony":{
		"displayName":"Coastal Symphony",
		"caption": '18" x 24" - Sold',
		"modalImages":"images/imagesOil/Symphony.jpg", 
		"thumb":"images/imagesOil/Symphony_thumb.jpg",
		"paintingClass":"seaOil",
		},
	"marsh":{
		"displayName":"Thomaston Marsh",
		"caption": '18" x 24" - Framed, $495',
		"modalImages":"images/imagesOil/Thomaston_Marsh.jpg", 
		"thumb":"images/imagesOil/Thomaston_Marsh_thumb.jpg",
		"paintingClass":"seaOil",
		},
	"turbulence":{
		"displayName":"Turbulence",
		"caption": 'Oil - 12" x 16"',
		"modalImages":"images/imagesOil/Turbulence.jpg", 
		"thumb":"images/imagesOil/Turbulence_thumb.jpg",
		"paintingClass":"seaOil",
		},


	"appleTree":{
		"displayName":"Apple Tree II",
		"caption": 'Mixed Media - 11" x 14", Matted and Framed - Sold',
		"modalImages":"images/imagesGold/Apple_Tree.jpg", 
		"thumb":"images/imagesGold/Apple_Tree.jpg",
		"paintingClass":"gold",
		},
	"autumnFarewell":{
		"displayName":"Autumn Farewell",
		"caption": 'Mixed Media - Matted and Framed - 12"x12" $125',
		"modalImages":"images/imagesGold/Autumn_Farewell.jpg", 
		"thumb":"images/imagesGold/Autumn_Farewell.jpg",
		"paintingClass":"gold",
		},
	"beneathSea":{
		"displayName":"Beneath the Sea",
		"caption": 'Mixed Media - Matted and Framed Size - 12"x12" $125',
		"modalImages":"images/imagesGold/Beneath_the_Sea.jpg", 
		"thumb":"images/imagesGold/Beneath_the_Sea.jpg",
		"paintingClass":"gold",
		},
	"imaginings":{
		"displayName":"Imaginings I",
		"caption": 'Mixed Media - Matted & Framed, 12" x 12" - SOLD',
		"modalImages":"images/imagesGold/Imaginings.jpg", 
		"thumb":"images/imagesGold/Imaginings.jpg",
		"paintingClass":"gold",
		},
	"julyGarden":{
		"displayName":"July Garden",
		"caption": 'Abstract, 5" x 5" - Mixed Media',
		"modalImages":"images/imagesGold/July_Garden.jpg", 
		"thumb":"images/imagesGold/July_Garden.jpg",
		"paintingClass":"gold",
		},
	"justBecause":{
		"displayName":"Just Because",
		"caption": 'Mixed Media 5" x 5"',
		"modalImages":"images/imagesGold/Just_Because.jpg", 
		"thumb":"images/imagesGold/Just_Because.jpg",
		"paintingClass":"gold",
		},
	"Milkweed":{
		"displayName":"Milkweed Pod",
		"caption": 'Abstract - 11" x 14" Matted & Framed - Mixed Media',
		"modalImages":"images/imagesGold/Milkweed_Pod.jpg", 
		"thumb":"images/imagesGold/Milkweed_Pod.jpg",
		"paintingClass":"gold",
		},
	"Nasturtiums":{
		"displayName":"Nasturtium Sisters",
		"caption": 'Mixed Media Framed Size: 15 x 15',
		"modalImages":"images/imagesGold/Nasturiums.jpg", 
		"thumb":"images/imagesGold/Nasturiums.jpg",
		"paintingClass":"gold",
		},
	"powderPuff":{
		"displayName":"Powder Puff",
		"caption": 'Mixed Media - Framed size: 12 x 12',
		"modalImages":"images/imagesGold/Powder_Puff.jpg", 
		"thumb":"images/imagesGold/Powder_Puff.jpg",
		"paintingClass":"gold",
		},
	"Sky":{
		"displayName":"Watercolor Sky",
		"caption": 'Mixed Media: 12" x 12"',
		"modalImages":"images/imagesGold/Sky.jpg", 
		"thumb":"images/imagesGold/Sky.jpg",
		"paintingClass":"gold",
		},
	"waitingWind":{
		"displayName":"Waiting for the Wind",
		"caption": 'Mixed Media - Framed 18" x 22" SOLD',
		"modalImages":"images/imagesGold/Waiting_for_the_Wind.jpg", 
		"thumb":"images/imagesGold/Waiting_for_the_Wind_thumb.jpg",
		"paintingClass":"gold",
		}



	};
